# Generated by Django 3.2.7 on 2021-09-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_staff_date_joined'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('comment', models.TextField(blank=True, null=True)),
                ('parents_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, choices=[('1', 'Appear'), ('2', 'Deleted')], default=1, max_length=150, null=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.markaz')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('1', 'Appear'), ('2', 'Disappear')], max_length=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.markaz')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
