# Generated by Django 3.2.7 on 2021-11-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20211122_1844'),
        ('lead', '0005_alter_lead_status'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='students',
            name='lead_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.place'),
        ),
        migrations.AddField(
            model_name='students',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('1', 'Paid'), ('2', 'Unpaid')], default=2, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='action',
            field=models.CharField(blank=True, choices=[(True, True), (False, False)], max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='students',
            name='group',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ManyToManyField(null=True, to='group.Group'),
        ),
    ]
