# Generated by Django 3.2.7 on 2021-11-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211122_1844'),
        ('main', '0024_room_typ'),
        ('group', '0002_auto_20211122_1844'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='teacher',
        ),
        migrations.AddField(
            model_name='category',
            name='markaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
        ),
        migrations.AddField(
            model_name='category',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='markaz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
        migrations.AddField(
            model_name='expense',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='learner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='markaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff'),
        ),
        migrations.AddField(
            model_name='salary',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Naqd pul'), ('2', 'UZCARD/HUMO'), ('3', 'Bank hisobi')], default=1, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Everybody'), ('2', 'Single')], default=1, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Percent'), ('2', 'Cash'), ('3', 'Salary')], max_length=150, null=True),
        ),
    ]
