# Generated by Django 3.2.7 on 2021-11-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20211125_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='staff',
        ),
    ]
