# Generated by Django 3.2.7 on 2021-12-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_course_photo'),
        ('payment', '0004_remove_expense_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
    ]
