# Generated by Django 3.2.7 on 2021-09-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_staff_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('days', models.CharField(choices=[('1', 'Toq kunlari'), ('2', 'Juft kunlar'), ('3', 'Dam olish kuni'), ('4', 'Har kuni'), ('5', 'Boshqa')], max_length=150)),
                ('start_lesson_at', models.CharField(max_length=150)),
                ('start_group_at', models.DateField()),
                ('finish_group_at', models.DateField()),
                ('type', models.CharField(choices=[('1', 'Appear'), ('2', 'Deleted')], default=1, max_length=150)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course')),
                ('markaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.markaz')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
                ('week', models.ManyToManyField(to='group.Week')),
            ],
        ),
    ]
