# Generated by Django 3.2.7 on 2021-11-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_room_typ'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='typ',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Jarayonda', 'Jarayonda'), ('Ochirilgan', 'Ochirilgan')], default='Yangi', max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='days',
            field=models.CharField(choices=[('Toq kunlari', 'Toq kunlari'), ('Juft kunlar', 'Juft kunlar'), ('Dam olish kuni', 'Dam olish kuni'), ('Har kuni', 'Har kuni'), ('Boshqa', 'Boshqa')], max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='markaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_lesson_at',
            field=models.TimeField(max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='week',
            field=models.ManyToManyField(blank=True, to='group.Week'),
        ),
    ]
