# Generated by Django 3.2.7 on 2021-09-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='markaz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
        ),
    ]
