# Generated by Django 3.2.7 on 2021-09-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_markaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True)),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Administrator', 'Administrator'), ('Teacher', 'Teacher'), ('Marketer', 'Marketer'), ('Cashier', 'Cashier'), ('Owner', 'Owner')], max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('markaz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
