# Generated by Django 3.2.7 on 2021-09-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staff_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='subdomain',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
