# Generated by Django 3.2.7 on 2021-09-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bot_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='own',
            field=models.BooleanField(default=True),
        ),
    ]
