# Generated by Django 3.2.7 on 2021-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210925_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='own',
            field=models.BooleanField(default=False),
        ),
    ]
