# Generated by Django 3.2.7 on 2021-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_message_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
