# Generated by Django 3.2.7 on 2021-10-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGraduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('markaz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz')),
            ],
        ),
    ]
