# Generated by Django 3.2.7 on 2021-10-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_coursecategory_courseplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
            preserve_default=False,
        ),
    ]
