# Generated by Django 3.2.7 on 2021-11-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
