# Generated by Django 3.2.7 on 2021-11-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_price_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Narx'},
        ),
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='period',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
