# Generated by Django 3.2.7 on 2021-11-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211116_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default='Appear', max_length=150),
        ),
    ]
