# Generated by Django 3.2.7 on 2021-11-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_staff_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
