# Generated by Django 3.2.7 on 2021-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_room_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='typ',
            field=models.CharField(choices=[('Appear', 'Appear'), ('Delete', 'Delete')], default='Appear', max_length=10),
        ),
    ]
