# Generated by Django 3.2.7 on 2021-12-10 17:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='markaz',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_to),
        ),
    ]
