# Generated by Django 3.2.7 on 2021-09-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staff_date_joined'),
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='markaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.markaz'),
        ),
    ]
