# Generated by Django 3.2.7 on 2021-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_place_markaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('1', 'Yangi'), ('2', 'Aloqada')], default=1, max_length=150),
        ),
    ]
