# Generated by Django 3.2.7 on 2021-11-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Aloqada', 'Aloqada')], default='Yangi', max_length=150),
        ),
    ]
