# Generated by Django 3.2.7 on 2021-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Aloqada', 'Aloqada'), ('Delete', 'Delete')], default='Yangi', max_length=150),
        ),
    ]
